### PR TITLE
Reorganize files to make a cohesive book

### PR DESCRIPTION
**Pull request by mitchkeller**
This is a first step toward having a unified set of source for all of chapters 9 through 12. It sounds like Steve probably isn't making any further updates, but Matt is working on getting that confirmed this summer.

This should merge smoothly and a `git rebase master` from a working branch should update everything.

### CODE REVIEW

**Comment by mitchkeller** [comment]
OK, I slipped a couple more things in here, but this is ready to merge and I will stop doing any messing around on this branch now.

**Comment by mitchkeller** [comment]
Working on building a print version (mainly for a workbook), and I found a few things that weren't coded right. Pushed to this branch so they can be merged with the other things @nelong

**Comment by nelong** [comment]
Mitch,
Can you publish this reorganization branch to the main repository? That
will make it much easier for me to pull into my work on my fork.
I plan to work on the new sections of the chapter over the next week. Is
there anything else to work on?

Nick

**Comment by mitchkeller** [comment]
Just merge the PR on Github and then you can pull master from the main repo and merge it into your local branch.

**Comment by nelong** [comment]
I'm an idiot. I didn't notice that this was part of a pull request...
I hope your move is going well.

**Pull request merged**
