### PR TITLE
NL edits for preface, 12.1, and 12.5

### PR DESCRIPTION
**Pull request by nelong**
@mitchkeller I think we are starting to get rid of some of excess files (thank god we got rid of the extra scalar line integral file, that was messing with me). I think we need to get rid of main.ptx as well. The only other thing that I did not know how to handle was (in acknowledgements) you are listed at Morningside because that's where you were when you did testing for ACM. I also didn't change much in the acknowledgements since I didn't feel like I had more we would want to add yet.

### CODE REVIEW

**Comment by nelong** [comment]
@mitchkeller I just finished 12.3. I changed the placement of labels in a few plots in 12.3 and updated the sage code that is in the ptx files, but I did not pull in any svg or pdf since I am unsure of what process you want for these graphics. The code in the ptx and in the cocal project should line up and generate the same graphs. Let me know if you have any other questions.

**Comment by mitchkeller** [comment]
I'll give this a look later today or early this evening, but sounds like we're in a good place and I can just throw a few changes on top.

**Comment by nelong** [comment]
> 

We are in a very good place and I think that we have a good to very good version of the remaining sections that we can make excellent with this next set of edits and adding polish to the graphics.

**Comment by nelong** [comment]
12.4 looks good except for removing the footnote on the hyperlinks (that I think I added) to the Second Fundamental Theorem of Calculus. I wanted to let you decide on using the footnote or the hyperlink. 
The second issue with Section 12.4 is that Exercise 1 is about a vector potential function, which is not what we talk about. I'll have to look 
Since I am not building the webwork stuff, I can't see the problems to add the comments about a difference in notation. I will do that using my deploy version tomorrow (if you are done with these sections).

**Comment by mitchkeller** [comment]
This all looks good. Example 12.2.11 is an easy tweak to move things out of the `solution` element. I can do that right after I merge this so I will have it on a branch. 

The footnotes on the hyperlinks that go to the single variable text are, unfortunately, not removable…at least not without doing something that is "not recommended". I find them obnoxious for HTML, but I do see why they're there for actual print (not electronic PDF). I suggest that we just live with them for now because this is likely something where Rob can be persuaded to do something more sensible for electronic formats (or next summer I'll just work up something using `@component` and versions to make the electronic formats not produce the footnotes).

**Pull request merged**
